spring.application.name=makemytrip
server.port=8080

spring.data.mongodb.uri=mongodb+srv://bhagavathisharma8_db_user:Raya1880@main.zfpdvjl.mongodb.net/makemytrip?retryWrites=true&w=majority&tlsAllowInvalidCertificates=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration